package:
  name: minimal-traceback
  version: 0.0.0

source:
  git_url: https://github.com/dfroger/minimal-traceback

build:
  number: 0
  binary_relocation: true

requirements:
  build:
  run:

about:
  home: https://github.com/dfroger/minimal-traceback
  license: GPL

