package:
  name: minimal-traceback
  version: 0.0.1

source:
  fn: v0.0.1.tar.gz
  url: https://github.com/dfroger/minimal-traceback/archive/v0.0.1.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
  run:

about:
  home: https://github.com/dfroger/minimal-traceback
  license: GPL

