#!/usr/bin/env python

def options(opt):
    opt.load('compiler_c')

def configure(conf):
    conf.load('compiler_c')

def build(bld):
    bld.shlib(source='minimal_traceback.c', target='minimal_traceback')
    bld.install_files('${PREFIX}/include', ['minimal_traceback.h'])
